services:
  samanbooks:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=3.12.0
    container_name: samanbooks
    ports:
      - "5000:5000"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    env_file: .env
    environment:
      - LOG_UID=1000
      - LOG_GID=1000
    volumes:
      - ./instance:/app/instance:rw
      - ./app/static/uploads:/app/app/static/uploads:rw
    networks:
      - samanbooks-network

volumes:
  logs:
    driver: local

networks:
  samanbooks-network:
    name: samanbooks-network
    attachable: true
    driver: bridge